### ISSUE TITLE
Outputclone - remember last position

### ISSUE THREAD

**Issue by bluetardis** [pkulchenko/ZeroBranePackage#21]
Is there any way to set a position or have it default to last position?  Using multi monitors and it resets every time I load ZeroBraneStudio...

**Comment by pkulchenko** [comment]
Should be doable; I need to check on a couple of things.

**Comment by pkulchenko** [comment]
Peter, should be fixed now, but let me know if it doesn't work as I don't have multiple monitors to test on.
