### ISSUE TITLE
Setting a different display format for tables in the console for the torch7 plugin

### ISSUE THREAD

**Issue by farrajota** [pkulchenko/ZeroBranePackage#26]
Displaying table's values in the console when using the torch7 interpreter gets a little annoying. The output of a table is displayed only by an hexa number:
```
>>>a = {1,2,3}
>>>a
table: 0x41eb62b0
```

while in other Lua interpreters the table outputs in the following format

```
>>>a = {1,2,3}
>>>a
{1, 2, 3} --[[table: 0x41eb62b0]]
```

My question is how to setup the torch7 interpreter to output tables like in the previous form so its easier to visualize its con

**Comment by pkulchenko** [comment]
@farrajota, thank you for the report. Should be fixed now; give it a try.

**Comment by farrajota** [comment]
@pkulchenko it works perfectly! Thank you.
