### ISSUE TITLE
Torch7 problem - continued

### ISSUE THREAD

**Issue by lnastansky** [pkulchenko/ZeroBranePackage#32]
Torch7 does not work ...

I did as suggested in posting March 29, 2016:

_______
@Orange15, I figured out what's happening. You have several options:

1) Point path.torch to th file: path.torch = [[/Users/mac/torch/install/bin/th]]. This will launch th instead of lua executable and it should be able to find its own libraries.

2) Point path.torch to install folder (not bin): path.torch = [[/Users/mac/torch/install/]]. You may get an error about libpaths having the wrong architecture, which is caused by the fact that lua executable that is included with the IDE is 32bit, but libraries and executables included with torch are 64bit. To fix that you may need to add path.lua = [[/Users/mac/torch/install/bin/luajit]], which will configure the IDE to use luajit from the torch install.
_______

Option 1) results in:

require 'nn'
error loading module 'libpaths' from file '/Users/Mac/torch/install/lib/lua/5.1/libpaths.so':
	dlopen(/Users/lMac/torch/install/lib/lua/5.1/libpaths.so, 6): no suitable image found.  Did find:
	/Users/Mac/torch/install/lib/lua/5.1/libpaths.so: mach-o, but wrong architecture
	[C]: at 0x00091340
	[C]: in function 'require'
	...Mac/torch/install/share/lua/5.1/paths/init.lua:1: in main chunk
	[C]: in function 'require'
	...Mac/torch/install/share/lua/5.1/torch/init.lua:12: in main chunk
	[C]: in function 'require'
	.../Mac/torch/install/share/lua/5.1/nn/init.lua:1: in main chunk

Option 2) results in:

require 'nn'
module 'nn' not found:
	no field package.preload['nn']
	no file '/Users/Mac/install/share/lua/5.1/nn.lua'
	no file '/Users/lMac/install/share/lua/5.1/nn/init.lua'
	no file '/Users/Mac/share/lua/5.1/nn.lua'
	etc. etc.

Any idea what to do?

Ludwig

**Comment by pkulchenko** [comment]
>> 1) Point path.torch to th file: path.torch = [[/Users/mac/torch/install/bin/th]]. This will launch th instead of lua executable and it should be able to find its own libraries.

> Option 1) results in:
> require 'nn'
> error loading module 'libpaths' from file '/Users/Mac/torch/install/lib/lua/5.1/libpaths.so':
> dlopen(/Users/lMac/torch/install/lib/lua/5.1/libpaths.so, 6): no suitable image found. Did find:
> /Users/Mac/torch/install/lib/lua/5.1/libpaths.so: mach-o, but wrong architecture

@lnastansky, are you trying to run this from the Local console? This is not going to work as the IDE is 32bit and the modules that come with torch are likely 64bit (this is why you get "wrong architecture"). If you are running this from a script, it should all work.

> Option 2) results in:
> require 'nn'
> module 'nn' not found:

Again, is this from a script or from a local console? Where is nn library installed on your machine?

**Comment by lnastansky** [comment]
Yes, I was using the local console.
If I am running from a script , all works!

Thank you - Ludwig
