### ISSUE TITLE
[torch] IDE is unable to find th in the correct location

### ISSUE THREAD

**Issue by Ark-kun** [pkulchenko/ZeroBranePackage#34]
I've added the torch7.lua plugin to ZBS v 1.30.
When I try running any script with Torch7 or QLua interpreter selected, I get the following error:
>Can't find qlua in any of the folders in PATH or TORCH_BIN: /home/alevol/nn/torch/install/bin, /home/alevol/nn/torch/install/bin, /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /usr/local/games, /home/alevol/bin
It's unable to find `/home/alevol/nn/torch/install/bin/th` in those dirs.

I've tried to paste parts of the script to ZBS's Local console and it worked as intended:
```
function findCmd(cmd, env)
  local path = (os.getenv('PATH') or '')..sep
             ..(env or '')..sep
             ..(os.getenv('HOME') and os.getenv('HOME') .. '/bin' or '')
  local paths = {}
  local res
  for p in path:gmatch("[^"..sep.."]+") do
    res = res or GetFullPathIfExists(p, cmd)
    table.insert(paths, p)
  end

  if not torch then
    DisplayOutputLn(("Can't find %s in any of the folders in PATH or TORCH_BIN: "):format(cmd)
      ..table.concat(paths, ", "))
    return
  end
  return res
end
findCmd('th')
"/home/alevol/nn/torch/install/bin/th"
findCmd(win and 'th.bat ' or 'th', os.getenv('TORCH_BIN'))
"/home/alevol/nn/torch/install/bin/th"
```

How can I fix this?

**Comment by pkulchenko** [comment]
@Ark-kun, thank you for the report! Should be fixed now; give it a try.
