### ISSUE TITLE
some plugins throw runtime error when editor is empty

### ISSUE THREAD

**Issue by smsrkr** [pkulchenko/ZeroBranePackage#38]
When the editor is empty, ie no files are open, some plugins cause a runtime error.
Especially `overtype.lua`, `tildemenu.lua`, and `wordwrapmenu.lua` make the Edit menu unusable.

**Comment by pkulchenko** [comment]
@smsrkr, thanks you for the report; should be fixed now.

**Comment by smsrkr** [comment]
Nice.
One more remains: `popupmenu.lua` has an active menu item and can be selected to spawn an error.
