### ISSUE TITLE
Fork() failed: can't run EVAL in debugging mode.

### ISSUE THREAD

**Issue by prochan2** [pkulchenko/ZeroBranePackage#41]
Following https://redislabs.com/blog/zerobrane-studio-plugin-for-redis-lua-scripts#.WG0vZ_krIUE:

#### My program:

    return redis.call('ping')

#### Redis version:
3.2.3 (Azure Redis Cache)

#### When executing:

> Program starting as '"C:\Data\Packages\ZeroBraneStudioEdu-1.5.0\bin\lua.exe" "C:\Data\Packages\ZeroBraneStudioEdu-1.5.0\packages\redis.lua" --instance redis://localhost:6380 --controller PcName:8172 --debug no --password "***" "C:\Data\Packages\ZeroBraneStudioEdu-1.5.0\myprograms\untitled.lua"'.
Program 'lua.exe' started in 'C:\Data\Packages\ZeroBraneStudioEdu-1.5.0\myprograms' (pid: 10512).
PONG
Program completed in 0.23 seconds (pid: 10512).

#### When debugging:

> Program starting as '"C:\Data\Packages\ZeroBraneStudioEdu-1.5.0\bin\lua.exe" "C:\Data\Packages\ZeroBraneStudioEdu-1.5.0\packages\redis.lua" --instance redis://localhost:6380 --controller PcName:8172 --debug yes --password "***" "C:\Data\Packages\ZeroBraneStudioEdu-1.5.0\myprograms\untitled.lua"'.
Program 'lua.exe' started in 'C:\Data\Packages\ZeroBraneStudioEdu-1.5.0\myprograms' (pid: 14512).
Fork() failed: can't run EVAL in debugging mode.
Program completed in 0.23 seconds (pid: 14512).

Is it because of my Redis version?

**Comment by itamarhaber** [comment]
Yep, looks like Azure Redis does not support the Lua Debugger.

**Comment by pkulchenko** [comment]
@itamarhaber, but 3.2.3 should include the debugger, no? Or did they limit it somehow?

**Comment by itamarhaber** [comment]
The Windows fork is different, and on top of that there's the fact that
this is the hosted version - I don't follow up on these as they are not in
the mainstream but I would suspect they won't have despite the version
number.

**Comment by pkulchenko** [comment]
ok; closing then unless there are some additional details or suggestions to test.
