### ISSUE TITLE
Please add opportunity to use system LUA

### ISSUE THREAD

**Issue by Mirocow** [pkulchenko/ZeroBranePackage#42]

**Comment by pkulchenko** [comment]
Not sure if there is anything specific to the packages in this request (if not, it should have been opened in [ZeroBraneStudio repository](https://github.com/pkulchenko/ZeroBraneStudio/issues) instead), but it's already available using `path.lua` option (and its variants for other lua versions) as [described in the documentation](https://studio.zerobrane.com/doc-general-preferences#interpreter-path).

**Comment by Mirocow** [comment]
thx
