### ISSUE TITLE
OpenRA Update incoming

### ISSUE THREAD

**Issue by StormWingDelta** [pkulchenko/ZeroBranePackage#43]
There's a new playtest out on their end so the openra.lua file will need updating soon.

**Comment by pkulchenko** [comment]
Is this just an FYI about the coming pull request? If so, it's probably not needed, you can just submit a pull request with the changes ;).

If you actually *want* those changes, you need to contact @Mailaender, as he authored the previous changes for OpenRA.

**Comment by Mailaender** [comment]
You can use `OpenRA.Utility.exe all --zbstudio-lua-api > openra.lua` to auto-generate a new file.
