### ISSUE TITLE
Request: Give access to application GitKraken

### ISSUE THREAD

**Issue by cpeosphoros** [pkulchenko/ZeroBranePackage#47]
GitKraken can be found here: https://github.com/settings/connections/applications/a7557949433b7d282a76

**Comment by pkulchenko** [comment]
Why does it need repo access? The repository is publicly available...

**Comment by cpeosphoros** [comment]
I don't know. I'm getting this error when trying to push:

![screenshot from 2017-07-21 13-48-37](https://user-images.githubusercontent.com/748982/28473561-86d39994-6e1b-11e7-95ae-b9a182e9e8ea.png)

**Comment by pkulchenko** [comment]
You don't have permissions to push there; you need to push to your own fork and submit a pull request.

**Comment by cpeosphoros** [comment]
Ah, allright, thanks.
