### ISSUE TITLE
Strange wxLua Runtime error crashes Zerobrane studio

### ISSUE THREAD

**Issue by RajKumar1605** [pkulchenko/ZeroBranePackage#60]
![what](https://user-images.githubusercontent.com/20901894/33477075-4dd8d922-d6aa-11e7-8a36-20970d54ded0.png)

**Comment by pkulchenko** [comment]
@RajKumar1605, what version of the IDE are you using and what were you trying to do when this happened?

**Comment by RajKumar1605** [comment]
@pkulchenko it was version 6 when the error first occurred. Then someone in love2D forums suggested to update the IDE as that might solve the issue. So I updated to the latest version 7 but the error is still happening.

Nothing, I am just typing code in the IDE and then suddenly this happened.

**Comment by pkulchenko** [comment]
What exactly are you typing when this happens? What's the smallest file that you can reproduce this on?

**Comment by pkulchenko** [comment]
I've been able to reproduce the issue, but I'd still be interested to see what API method you are typing when this happens.

**Comment by pkulchenko** [comment]
Opened issue in the proper repository for it: https://github.com/pkulchenko/ZeroBraneStudio/issues/837. Will push a fix shortly, so closing this one.
