### ISSUE TITLE
Redis: Enhancement request: Implement workaround for 'Step Over (Shift+F10)'

### ISSUE THREAD

**Issue by tw-bert** [pkulchenko/ZeroBranePackage#64]
redis.lua: 0.36 redis 4.0.6

Redis itself currently does not support 'Step Over'. In ZBS, 'Step Over'/'Step Into'/.'Step Out' all perform the same function: 'Step Into'.

Would it be easy to implement the following workaround?
- If 'Step Over' is requested (Shift+F10): 
- Let ZBS set a (possibly hidden) temporary breakpoint at the next executable source code line (this might be the tricky part)
- Let ZBS do a 'Continue'
- Let ZBS remove the temporary breakpoint

This would enhance the flow tremendously.

**Comment by pkulchenko** [comment]
> Redis itself currently does not support 'Step Over'. In ZBS, 'Step Over'/'Step Into'/.'Step Out' all perform the same function: 'Step Into'.

Right; this is the current limitation of the Redis debugger.

> Let ZBS set a (possibly hidden) temporary breakpoint at the next executable source code line (this might be the tricky part)

I don't think it's possible without some combination of static and run-time analysis, as you'd need to know things like whether the last loop operator is really the last one or not (depending on the current value) or where the control will jump after `break` and many other similar things.

The IDE already provides `Run To Cursor` (currently linked to `Ctrl+Shift+F10`), so you can either use that, or remap it to `Shift+F10`, but you'll need to move the cursor to the target position before invoking it.

I don't think there is much else that I can offer, unless you can come up with some simple logic to detect the "next" executable line.

**Comment by tw-bert** [comment]
Makes sense, thanks for your insights.

**Comment by itamarhaber** [comment]
> I don't think there is much else that I can offer, unless you can come up with some simple logic to detect the "next" executable line.

I think Intel has this wonderful tech ;)

**Comment by pkulchenko** [comment]
> I think Intel has this wonderful tech ;)

Indeed ;).

@itamarhaber, since you are stopping by, any insight into 1024 limit and `'<eof>' expected` error in #62?

**Comment by itamarhaber** [comment]
@pkulchenko certainly - seems like my notifications are broken though :(
