### ISSUE TITLE
Redis: Float precision is lost in Stack and Remote Console

### ISSUE THREAD

**Issue by tw-bert** [pkulchenko/ZeroBranePackage#66]
Redis `4.0.8`, redis.lua `0.36`

High precision floats/doubles (numbers) have precision loss, while viewing for debugging only.
The actual value is fine, but can't be shown in ZeroBrane.
I have no idea if this is a Redis limitation or a ZeroBrane limitation.

See the following code:
```lua
    request_curr.now = request_argv.now 
    request_curr.now_debug_str = string.format("%015.6f",request_argv.now) -- Just for debugging, to show no precision has been lost. This is near impossible to see from ZeroBrane and/or Redis stack directly.
```

And the Stack:
![image](https://user-images.githubusercontent.com/3413888/36097236-5a9d99e8-0ffa-11e8-9386-aa2193a15752.png)
(obviously, 'now' has lost precision)
Remote Console gives similar issues.

I tried (`user.lua`):
```lua
debugger.numformat = "%015.15f"
```
But that gives:
![image](https://user-images.githubusercontent.com/3413888/36097292-a8467d22-0ffa-11e8-88e7-77daf9214fd9.png)

**Comment by pkulchenko** [comment]
> I have no idea if this is a Redis limitation or a ZeroBrane limitation.

As far as I remember, it was Redis limitation; you may be able to confirm if you turn `verbose` option on, as it will show details on what was sent and received from Redis: `redis = {verbose = true}`.

**Comment by tw-bert** [comment]
Checked:
```lisp
<redis rcvd> +<value> request_curr = {[\"now\"]=2.01802e+07; [\"now_debug_str\"]=\"20180212.104500\";}
```

_(@pkulchenko:)_
> As far as I remember, it was Redis limitation

Yes, that's my conclusion as well: Redis limitation / issue. @itamarhaber : Is there a setting or parameter to set the redis-side serialization format for floats?

**Comment by pkulchenko** [comment]
ok; thank you for the update. closing.
