### ISSUE TITLE
hidemenu plugin disables all menu shortcuts

### ISSUE THREAD

**Issue by moteus** [pkulchenko/ZeroBranePackage#82]
In case of `hidden` menu all shourtcuts associeted with minu items stop working (e.g. F5/F6 to run)

**Comment by pkulchenko** [comment]
@moteus, indeed, but there is not much I can do, as it's how wxwidgets works. It may be possible to move those shortcuts to the accelerator table, but it's probably overkill for this plugin. For now the workaround is to use `Alt` to access the menu. If you find a better way to handle this, please update this ticket.
