### ISSUE TITLE
replace in files

### ISSUE THREAD

**Issue by qgenesist** [pkulchenko/ZeroBranePackage#91]
I believe I am on the lastest version. W10 updates up to date.

I search for _cfn replace _CFN Aa button active. activate replace all button. finds 38 in 4 files. put my cursor in the results box and save. save all is greyed out. it saves 0. what are the actual steps and  order to save these changes? It always comes as a surprise to me when it work, which it does sometimes. I must not understand the steps.

**Comment by pkulchenko** [comment]
>I search for _cfn replace _CFN Aa button active. activate replace all button. finds 38 in 4 files. 

So far so good.

> put my cursor in the results box and save. save all is greyed out. it saves 0.

One, you shouldn't put the cursor in the search results tab, as it should already be there.
Two, the name for the tab with search results should look like `* Search Results: _cfn`, with `*` indicating that there are some changes that need to be saved. Selecting `Save` or `Ctrl-S` should save those changes and add "Updated X lines in Y files" message to the end of the search window. If that doesn't happen, what text does it show after `Searched for '_cfn'` message when the search is done?

**Comment by pkulchenko** [comment]
>  I cannot reproduce the problem at will.

So, in this case everything works as expected, right?

> Context lines (if any) are used as safety checks during the update. (save and save all are greyed out)

Is the cursor in the Search Results window? The only reason for `Save` to be greyed out if the Search Results window is not active. Can you click on it and see if Save becomes available?

**Comment by qgenesist** [comment]
searched for _cfp change to _CFP found 42 shows : lines saved now. but I have been placing my cursor in search results window  I will update next time it happens (its usually when I have about 10 windows open and have made many changes over 3 or 4 plugins (fh plugins not zb plugins)

________________________________

**Comment by pkulchenko** [comment]
Thank you for the update. Just a quick comment: Save All doesn't take Search Result windows into account to avoid the risk of saving them by mistake. Each Search Result window needs to be saved individually (with it being an active window).

I'll consider revising the text at the bottom to make it clear (that the window needs to be active to save).

**Comment by pkulchenko** [comment]
Closing, as it's not an issue with any of the packages.
